name: Bug Report
description: Report a bug in the image optimization system
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us fix it.
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: |
        When I try to...
        I expected...
        But instead...
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Place image in original/
        2. Run `make optimize`
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or logs
      render: shell
      placeholder: |
        Paste any relevant error messages here
        
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: How are you running the optimization?
      options:
        - Docker (make commands)
        - Docker (npm run docker commands)
        - Node.js directly (npm commands)
        - GitHub Actions
    validations:
      required: true
      
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: macOS 14.0, Ubuntu 22.04, Windows 11
    validations:
      required: true
      
  - type: input
    id: node-version
    attributes:
      label: Node.js Version (if applicable)
      description: Output of `node --version`
      placeholder: v20.11.0
      
  - type: input
    id: docker-version
    attributes:
      label: Docker Version (if applicable)
      description: Output of `docker --version`
      placeholder: Docker version 24.0.7
      
  - type: dropdown
    id: image-format
    attributes:
      label: Image Format
      description: What format was the problematic image?
      multiple: true
      options:
        - PNG
        - JPEG/JPG
        - GIF
        - WebP
        - AVIF
        - Other
        
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've checked existing issues for duplicates
        - label: I've included all error messages
        - label: I can provide a sample image that reproduces the issue