name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Coverage Report
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const fs = require('fs');
          try {
            const coverage = JSON.parse(fs.readFileSync('./coverage/coverage-summary.json', 'utf8'));
            const total = coverage.total;
            
            const formatPercent = (num) => `${num.toFixed(1)}%`;
            
            const comment = `## 📊 Test Coverage Report
            
            | Metric | Coverage |
            |--------|----------|
            | Statements | ${formatPercent(total.statements.pct)} |
            | Branches | ${formatPercent(total.branches.pct)} |
            | Functions | ${formatPercent(total.functions.pct)} |
            | Lines | ${formatPercent(total.lines.pct)} |
            
            ✅ All tests passed!`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          } catch (error) {
            console.log('Coverage report not available');
          }